#
# SPDX-License-Identifier: Apache-2.0
#
---
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=IBM-Blockchain.generator-fabric"
      - "status-success=DCO"
    actions:
      merge:
        method: merge
  - name: Automatic merge for dependabot
    conditions:
      - "author=dependabot-preview[bot]"
      - "status-success=IBM-Blockchain.generator-fabric"
      - "status-success=DCO"
    actions:
      merge:
        method: merge