#
# SPDX-License-Identifier: Apache-2.0
#
---
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=Build (Linux)"
      - "status-success=Build (macOS)"
      - "status-success=Build (Windows)"
      - "status-success=Tests (Chaincode)"
      - "status-success=Tests (Contracts w/ private data)"
      - "status-success=Tests (Contracts)"
      - "status-success=Tests (Networks)"
      - "status-success=DCO"
    actions:
      merge:
        method: merge
        strict: true
        strict_method: merge
  - name: Automatic merge for dependabot
    conditions:
      - "author=dependabot-preview[bot]"
      - "status-success=Build (Linux)"
      - "status-success=Build (macOS)"
      - "status-success=Build (Windows)"
      - "status-success=Tests (Chaincode)"
      - "status-success=Tests (Contracts w/ private data)"
      - "status-success=Tests (Contracts)"
      - "status-success=Tests (Networks)"
      - "status-success=DCO"
    actions:
      review:
        type: APPROVE
        message: LGTM
      merge:
        method: merge
        strict: true
        strict_method: merge