#
# SPDX-License-Identifier: Apache-2.0
#

sudo: required
services:
    - docker
language: node_js
node_js:
    - "8"
script: |
    set -ex
    npm audit
    npm test
    ./scripts/run-integration-tests.sh
