#
# SPDX-License-Identifier: Apache-2.0
#
---
name: Audit
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch: {}
jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Run script
        id: run
        run: |
          scripts/run-npm-audit-fix.sh
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "::set-output name=changes::yes"
          else
            echo "::set-output name=changes::no"
          fi
      - name: Set GitHub user name and email
        env:
          AUTO_GITHUB_NAME: ${{ secrets.AUTO_GITHUB_NAME }}
          AUTO_GITHUB_EMAIL: ${{ secrets.AUTO_GITHUB_EMAIL }}
        run: |
          git config --global user.name ${AUTO_GITHUB_NAME}
          git config --global user.email ${AUTO_GITHUB_EMAIL}
          git config --local --unset-all http.${GITHUB_SERVER_URL}/.extraheader
        if: steps.build.outputs.changes == 'yes'
      - name: Commit version bump
        run: |
          VERSION=$(jq -r ".version" package.json)
          git commit -asm "Automatic version bump to ${VERSION}"
        if: steps.build.outputs.changes == 'yes'
      - name: Push commit to GitHub
        env:
          AUTO_GITHUB_NAME: ${{ secrets.AUTO_GITHUB_NAME }}
          AUTO_GITHUB_ACCESS_TOKEN: ${{ secrets.AUTO_GITHUB_ACCESS_TOKEN }}
        run: |
          git -c http.extraheader="Authorization: Basic $(echo -n ${AUTO_GITHUB_NAME}:${AUTO_GITHUB_ACCESS_TOKEN} | base64)" push ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} HEAD:master -f
        if: steps.build.outputs.changes == 'yes'
